"""update_book_edition_with_isbn_number_field

Revision ID: 05f423df6b8d
Revises: 2e399d4a99e6
Create Date: 2025-08-15 13:06:05.788973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05f423df6b8d'
down_revision: Union[str, Sequence[str], None] = '2e399d4a99e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add isbn_number column as nullable first
    op.add_column('bookedition', sa.Column('isbn_number', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=True))
    
    # Migrate data: copy isbn_13 to isbn_number, fallback to isbn_10 if isbn_13 is null
    op.execute("""
        UPDATE bookedition 
        SET isbn_number = COALESCE(isbn_13, isbn_10)
        WHERE isbn_13 IS NOT NULL OR isbn_10 IS NOT NULL
    """)
    
    # Make isbn_number NOT NULL now that we have data
    op.alter_column('bookedition', 'isbn_number', nullable=False)
    
    # Drop old indexes and columns
    op.drop_index(op.f('ix_bookedition_isbn_10'), table_name='bookedition')
    op.drop_index(op.f('ix_bookedition_isbn_13'), table_name='bookedition')
    op.drop_column('bookedition', 'isbn_13')
    op.drop_column('bookedition', 'isbn_10')
    
    # Create new index
    op.create_index(op.f('ix_bookedition_isbn_number'), 'bookedition', ['isbn_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookedition', sa.Column('isbn_10', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('bookedition', sa.Column('isbn_13', sa.VARCHAR(length=13), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bookedition_isbn_number'), table_name='bookedition')
    op.create_index(op.f('ix_bookedition_isbn_13'), 'bookedition', ['isbn_13'], unique=True)
    op.create_index(op.f('ix_bookedition_isbn_10'), 'bookedition', ['isbn_10'], unique=False)
    op.drop_column('bookedition', 'isbn_number')
    # ### end Alembic commands ###
