"""add_contact_person_field_to_suppliers_table

Revision ID: 06698a9ae896
Revises: f7d061503542
Create Date: 2025-09-10 00:09:01.968736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06698a9ae896'
down_revision: Union[str, Sequence[str], None] = 'f7d061503542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchaseorder', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('purchaseorder', 'expected_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('supplier', sa.Column('contact_person', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_supplier_contact_person'), 'supplier', ['contact_person'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_contact_person'), table_name='supplier')
    op.drop_column('supplier', 'contact_person')
    op.alter_column('purchaseorder', 'expected_delivery_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('purchaseorder', 'order_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
