"""update supplier table with relationships and repr method

Revision ID: 0f3feec45c92
Revises: fda9ca140962
Create Date: 2025-08-22 12:22:13.703534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f3feec45c92'
down_revision: Union[str, Sequence[str], None] = 'fda9ca140962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('supplier', sa.Column('payment_terms', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('supplier', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'status')
    op.drop_column('supplier', 'payment_terms')
    op.drop_column('supplier', 'category')
    # ### end Alembic commands ###
