"""Add SuperAdmin table

Revision ID: 3bcff576612e
Revises: 9502ef624d8a
Create Date: 2025-08-06 12:06:18.849078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bcff576612e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superadmin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superadmin_created_at'), 'superadmin', ['created_at'], unique=False)
    op.create_index(op.f('ix_superadmin_email'), 'superadmin', ['email'], unique=True)
    op.create_index(op.f('ix_superadmin_name'), 'superadmin', ['name'], unique=True)
    op.create_index(op.f('ix_superadmin_updated_at'), 'superadmin', ['updated_at'], unique=False)
    op.alter_column('auditlog', 'changed_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('publisher_tenant_id_fkey'), 'publisher', type_='foreignkey')
    op.drop_column('publisher', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publisher', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('publisher_tenant_id_fkey'), 'publisher', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('auditlog', 'changed_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_superadmin_updated_at'), table_name='superadmin')
    op.drop_index(op.f('ix_superadmin_name'), table_name='superadmin')
    op.drop_index(op.f('ix_superadmin_email'), table_name='superadmin')
    op.drop_index(op.f('ix_superadmin_created_at'), table_name='superadmin')
    op.drop_table('superadmin')
    # ### end Alembic commands ###
