"""add effective_date field to tax_rates table

Revision ID: 4272a37dbb38
Revises: fb5f61c6355a
Create Date: 2025-08-25 18:22:31.546065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4272a37dbb38'
down_revision: Union[str, Sequence[str], None] = 'fb5f61c6355a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxrates', sa.Column('effective_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxrates', 'effective_date')
    # ### end Alembic commands ###
