"""sync_user_model_with_database

Revision ID: 4d25068cd499
Revises: 8ee90759b182
Create Date: 2025-08-12 14:09:45.129241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d25068cd499'
down_revision: Union[str, Sequence[str], None] = '8ee90759b182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add phone_number as nullable first, then update to have default values, then make it NOT NULL
    op.add_column('user', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    op.add_column('user', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    
    # Update any NULL phone_number values to empty string
    op.execute("UPDATE \"user\" SET phone_number = '' WHERE phone_number IS NULL")
    
    # Now make phone_number NOT NULL
    op.alter_column('user', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=15),
               nullable=False)
    
    op.alter_column('user', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('user', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
