"""add_profit_discount_columns_and_computed_sale_price

Revision ID: 60a3d9ecea8e
Revises: 05f423df6b8d
Create Date: 2025-08-15 13:44:54.543927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a3d9ecea8e'
down_revision: Union[str, Sequence[str], None] = '05f423df6b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns as nullable first
    op.add_column('inventory', sa.Column('profit', sa.Numeric(scale=4), nullable=True))
    op.add_column('inventory', sa.Column('discount', sa.Numeric(scale=4), nullable=True))
    
    # Set default values for existing records
    op.execute("""
        UPDATE inventory 
        SET profit = 0.00, discount = 0.00 
        WHERE profit IS NULL OR discount IS NULL
    """)
    
    # Make columns NOT NULL now that we have data
    op.alter_column('inventory', 'profit', nullable=False)
    op.alter_column('inventory', 'discount', nullable=False)
    
    # Drop the old sale_price column
    op.drop_column('inventory', 'sale_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('sale_price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('inventory', 'discount')
    op.drop_column('inventory', 'profit')
    # ### end Alembic commands ###
