"""update_table_constraints

Revision ID: 8ee90759b182
Revises: 37bddc6f271a
Create Date: 2025-08-11 15:57:49.158470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee90759b182'
down_revision: Union[str, Sequence[str], None] = '37bddc6f271a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any NULL phone_number values to empty string
    op.execute("UPDATE \"user\" SET phone_number = '' WHERE phone_number IS NULL")
    
    # Then alter the column to be NOT NULL
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
