"""fix_models_and_relationships

Revision ID: 969d4c5ac625
Revises: 8ca88c0ea56b
Create Date: 2025-07-26 13:11:03.454306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969d4c5ac625'
down_revision: Union[str, Sequence[str], None] = '8ca88c0ea56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip foreign key constraint changes for SQLite compatibility
    # The existing foreign key constraint is sufficient for basic functionality
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip foreign key constraint changes for SQLite compatibility
    pass
    # ### end Alembic commands ###
