"""drop publishers

Revision ID: a789e33ea9a6
Revises: cbdbb578cbfb
Create Date: 2025-08-13 17:13:44.797276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a789e33ea9a6'
down_revision: Union[str, Sequence[str], None] = 'cbdbb578cbfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_created_at'), table_name='publisher')
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_index(op.f('ix_publisher_updated_at'), table_name='publisher')
    op.drop_table('publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publisher',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('publisher_pkey'))
    )
    op.create_index(op.f('ix_publisher_updated_at'), 'publisher', ['updated_at'], unique=False)
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=True)
    op.create_index(op.f('ix_publisher_created_at'), 'publisher', ['created_at'], unique=False)
    # ### end Alembic commands ###
