"""add_description_column_to_tax_rates_table

Revision ID: d35b6022ba73
Revises: 06698a9ae896
Create Date: 2025-09-10 10:32:05.292762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd35b6022ba73'
down_revision: Union[str, Sequence[str], None] = '06698a9ae896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxrates', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxrates', 'description')
    # ### end Alembic commands ###
