"""make_tenant_name_unique_and_not_nullable

Revision ID: ecac78ad9b28
Revises: 1f32060c8afc
Create Date: 2025-08-07 10:22:12.732487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecac78ad9b28'
down_revision: Union[str, Sequence[str], None] = '1f32060c8afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_name'), table_name='tenant')
    op.create_index(op.f('ix_tenant_name'), 'tenant', ['name'], unique=False)
    # ### end Alembic commands ###
