"""update_purchase_orders_to_use_editions

Revision ID: f766805fed7e
Revises: 169974515f8c
Create Date: 2025-08-13 18:50:36.070850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f766805fed7e'
down_revision: Union[str, Sequence[str], None] = '169974515f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchaseorder', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('purchaseorder', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=True)
    op.create_index(op.f('ix_purchaseorder_order_date'), 'purchaseorder', ['order_date'], unique=False)
    op.add_column('purchaseorderitems', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('purchaseorderitems', sa.Column('po_id', sa.Uuid(), nullable=False))
    op.add_column('purchaseorderitems', sa.Column('edition_id', sa.Uuid(), nullable=False))
    op.add_column('purchaseorderitems', sa.Column('quantity_ordered', sa.Integer(), nullable=False))
    op.alter_column('purchaseorderitems', 'unit_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('purchaseorderitems_book_id_fkey'), 'purchaseorderitems', type_='foreignkey')
    op.drop_constraint(op.f('purchaseorderitems_order_id_fkey'), 'purchaseorderitems', type_='foreignkey')
    op.create_foreign_key(None, 'purchaseorderitems', 'bookedition', ['edition_id'], ['edition_id'])
    op.create_foreign_key(None, 'purchaseorderitems', 'purchaseorder', ['po_id'], ['id'])
    op.drop_column('purchaseorderitems', 'quantity')
    op.drop_column('purchaseorderitems', 'book_id')
    op.drop_column('purchaseorderitems', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseorderitems', sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('purchaseorderitems', sa.Column('book_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('purchaseorderitems', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'purchaseorderitems', type_='foreignkey')
    op.drop_constraint(None, 'purchaseorderitems', type_='foreignkey')
    op.create_foreign_key(op.f('purchaseorderitems_order_id_fkey'), 'purchaseorderitems', 'purchaseorder', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('purchaseorderitems_book_id_fkey'), 'purchaseorderitems', 'book', ['book_id'], ['id'])
    op.alter_column('purchaseorderitems', 'unit_cost',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('purchaseorderitems', 'quantity_ordered')
    op.drop_column('purchaseorderitems', 'edition_id')
    op.drop_column('purchaseorderitems', 'po_id')
    op.drop_column('purchaseorderitems', 'id')
    op.drop_index(op.f('ix_purchaseorder_order_date'), table_name='purchaseorder')
    op.alter_column('purchaseorder', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('purchaseorder', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
