"""add_order_number_and_delivery_date_to_purchase_orders_and_contact_info_to_suppliers

Revision ID: f7d061503542
Revises: 4272a37dbb38
Create Date: 2025-09-03 15:53:46.556517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7d061503542'
down_revision: Union[str, Sequence[str], None] = '4272a37dbb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaseorder', sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('purchaseorder', sa.Column('expected_delivery_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_purchaseorder_expected_delivery_date'), 'purchaseorder', ['expected_delivery_date'], unique=False)
    op.create_index(op.f('ix_purchaseorder_order_number'), 'purchaseorder', ['order_number'], unique=True)
    op.add_column('supplier', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('supplier', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'address')
    op.drop_column('supplier', 'phone_number')
    op.drop_index(op.f('ix_purchaseorder_order_number'), table_name='purchaseorder')
    op.drop_index(op.f('ix_purchaseorder_expected_delivery_date'), table_name='purchaseorder')
    op.drop_column('purchaseorder', 'expected_delivery_date')
    op.drop_column('purchaseorder', 'order_number')
    # ### end Alembic commands ###
