"""update_sales_and_sale_items_tables_with_payment_and_customer_fields

Revision ID: fda9ca140962
Revises: 60a3d9ecea8e
Create Date: 2025-08-21 10:28:50.805101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fda9ca140962'
down_revision: Union[str, Sequence[str], None] = '60a3d9ecea8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saleitems', sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    op.add_column('saleitems', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('saleitems', sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sales', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.add_column('sales', sa.Column('amount_received', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('change_given', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('sales', sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True))
    op.add_column('sales', sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'customer_email')
    op.drop_column('sales', 'customer_phone')
    op.drop_column('sales', 'customer_name')
    op.drop_column('sales', 'change_given')
    op.drop_column('sales', 'amount_received')
    op.drop_column('sales', 'payment_method')
    op.drop_column('saleitems', 'author')
    op.drop_column('saleitems', 'title')
    op.drop_column('saleitems', 'isbn')
    # ### end Alembic commands ###
